-- Add WarrantyStatus enum value
ALTER TYPE "WarrantyStatus" ADD VALUE IF NOT EXISTS 'ACTIVE';
ALTER TYPE "WarrantyStatus" ADD VALUE IF NOT EXISTS 'CLAIMED';
ALTER TYPE "WarrantyStatus" ADD VALUE IF NOT EXISTS 'EXPIRED';

-- Add ClaimStatus enum value
ALTER TYPE "ClaimStatus" ADD VALUE IF NOT EXISTS 'PENDING_REVIEW';
ALTER TYPE "ClaimStatus" ADD VALUE IF NOT EXISTS 'APPROVED';
ALTER TYPE "ClaimStatus" ADD VALUE IF NOT EXISTS 'REJECTED';
ALTER TYPE "ClaimStatus" ADD VALUE IF NOT EXISTS 'EXPIRED';

-- Add SupplierType enum value
ALTER TYPE "SupplierType" ADD VALUE IF NOT EXISTS 'TELEGRAM_BOT';
ALTER TYPE "SupplierType" ADD VALUE IF NOT EXISTS 'API';